#!/bin/sh
while read file
do
  case "$1" in

  # Edit
  "C-e")
    gimp "$file" ;;

  # Rotate 90 degrees
  "C-r")
    convert -rotate 90 "$file" "$file" ;;

  # Set as wallpaper
  "C-w")
    set-wallpaper "$file" ;;

  # Share
  "C-s")
    quickshare default "$file" ;;

  esac
done
