#!/bin/bash

source $HOME/.config/contextswitcher/main

xrandr \
  --output eDP1 --off \
  --output DP1 --mode 1920x1080 --pos 1366x0 --rotate normal \
  --output HDMI2 --mode 1366x768 --pos 0x0 --rotate normal \
  --output DP1-5 --off \
  --output DP1-6 --off \
  --output DP2 --off \
  --output HDMI1 --off \
  --output VIRTUAL1 --off

set-wallpaper &
