#!/bin/bash

HOST="$(< /etc/hostname)"
GUEST="${1:-kersthor}"

# Input
killall barriers
barriers \
  -f --name ${HOST} --disable-client-cert-checking \
  -c /home/grim/.config/barrier/default.conf --address :24800 \
  &
renice -n -10 -p $(pidof barrier{s,c})
ssh ${GUEST} renice -n -10 -p $(pidof barrier{s,c})

# Sound
pactl unload-module module-native-protocol-tcp
pactl load-module module-native-protocol-tcp
ssh ${GUEST} pactl unload-module module-tunnel-sink
ssh ${GUEST} pactl load-module module-tunnel-sink server=tcp:${HOST}

# Storage
mkdir -p ~/Anchor/${GUEST}
umount ~/Anchor/${GUEST}
sshfs -o transform_symlinks,follow_symlinks \
  ${GUEST}:${HOME} \
  ~/Anchor/${GUEST}
