#!/bin/bash

# Input
killall barriers
barriers \
  -f --name velok --disable-client-cert-checking \
  -c /home/grim/.config/barrier/default.conf --address :24800 \
  &
ssh vkec \
  flatpak run -p --command="barrierc" com.github.debauchee.barrier \
  --no-restart --no-tray --no-daemon --debug INFO \
  --name vkec \
  velok \
  &

# Sound
pactl unload-module module-native-protocol-tcp
pactl load-module module-native-protocol-tcp
ssh vkec pactl unload-module module-tunnel-sink
ssh vkec pactl load-module module-tunnel-sink server=tcp:velok
