#!/bin/sh

xrandr \
  --output DisplayPort-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal \
  --output DisplayPort-0 --off \
  --output DisplayPort-2 --off \
  --output HDMI-A-0 --off

barrierc -n kersthor velok &
renice -n -10 -p $(pidof barrier{s,c})

setxkbmap $(setxkbmap -query | grep "^layout:" | awk -F ": *" '{print $2}')
DISPLAY=:0 numlockx on

killall -9 picom

sleep 5 && pactl load-module module-tunnel-sink server=tcp:velok &
