#!/bin/bash

t_warn=${1:-82}
t_crit=${2:-95}

# sorting temp values for all cores
t_curr=($(sensors -u coretemp-isa-0000 | awk '/input/{ printf "%d\n", $2 }' | sort -r))

# using last value of array -> max temp ${t_curr[0]}
if [[ ${t_curr[0]} -lt $t_warn  ]];then
  color="#90A959" #green - base16
  exit 0
elif [[ ${t_curr[0]} -ge $t_warn  ]] && [[ ${t_curr[0]} -lt $t_crit  ]]; then
  color="#D28445" #orange - base16
else
  color="#AC4142" #red - base16
fi

# elements output for JSON (short text, full text, color)
echo "🌡 ${t_curr[0]}C"
echo "🌡 ${t_curr[0]}C"
echo "$color"
exit
