#!/usr/bin/env sh

export NNN_BMS="\
l:~/Library;\
p:~/Pictures;\
m:~/Music;\
c:~/Development;\
d:~/Download;\
t:~/Temporary;\
D:~/.dotfiles;\
T:~/.local/share/Trash/files;\
"

export NNN_PLUG="\
s:-_quickshare default \$nnn*;\
w:-_less -iR \$nnn*;\
"

export NNN_TRASH=1

