#!/bin/bash

# adbplaylist
# Sync a MPD playlist to an Android device via ADB
# GPLv3 - Grim Kriegor <grimkriegor@krutt.org> 2018

set -e

PLAYLIST="Mobile"
PLAYLIST_LOCATION="$HOME/.cache/mpd/playlists"
DESKTOP_MUSIC_LOCATION="$HOME/Music"
MOBILE_MUSIC_LOCATION="/sdcard/Music/Playlist"
TEMPORARY_MUSIC_LOCATION="/tmp/playlist"

[[ -d "$TEMPORARY_MUSIC_LOCATION" ]] || mkdir -p "$TEMPORARY_MUSIC_LOCATION"
while read line; do
  song=$(echo $line | awk -F "/" '{print $NF}')
  path="$DESKTOP_MUSIC_LOCATION/$line"
  cp "$path" "$TEMPORARY_MUSIC_LOCATION/"
done <"$PLAYLIST_LOCATION/$PLAYLIST.m3u"
adb-sync --delete "$TEMPORARY_MUSIC_LOCATION/" "$MOBILE_MUSIC_LOCATION"
rm -rf "$TEMPORARY_MUSIC_LOCATION"
adb shell am broadcast -a android.intent.action.MEDIA_MOUNTED -d file:///sdcard/Music
