#!/bin/sh

# Display Select
# GPLv3 - Grim Kriegor <grimkriegor@krutt.org>
# 2018

display_list=($(xrandr | grep -w "connected\|disconnected" | awk -F'[ +]' '{print $1}'))

menu="\
Manual selection
Laptop
VGA
HDMI
Dock HDMI
Projector
Laptop | VGA
VGA | Laptop
Laptop | HDMI
HDMI | Laptop
Laptop | Dock HDMI
Dock HDMI | Laptop
Mirrored VGA
Mirrored HDMI
Mirrored Dock HDMI"

if [ "$1" == "" ]; then
  menu_option=$(echo -e "$menu" | dmenu -i -p "display")
else
  menu_option="$1"
fi

function get_resolution() {
  display="$1"
  resolution=$(xrandr | grep -w connected | awk -F'[ +]' '{print $1,$3}' | grep "$display" | awk '{print $2}')
  echo "$resolution"
}

function exclusive() {
  display="$1"
  xrandr --output "$display" --auto
  for output in "${display_list[@]}"; do
    if [ "$output" != "$display" ]; then
      xrandr --output $output --off
    fi
  done
}

function side_by_side() {
  display="$1"
  display2="$2"
  xrandr --output "$display" --auto \
    --output "$display2" --auto --right-of "$display"
}

function mirror() {
  display="$1"
  display2="$2"
  display_resolution=$(get_resolution "$display")
  xrandr --output "$display" --auto \
    --output "$display2" --same-as "$display" --scale-from "$display_resolution"
}

function projector() {
  projector="$1"
  xrandr --output "$projector" --mode 1024x768 \
    --output LVDS1 --mode 1024x768 --same-as "$projector"
}

case "$menu_option" in
  "Manual selection")   arandr ;;
  "Laptop")             exclusive LVDS1 ;;
  "VGA")                exclusive VGA1 ;;
  "HDMI")               exclusive HDMI1 ;;
  "Dock HDMI")          exclusive HDMI2 ;;
  "Projector")          projector VGA1 ;;
  "Laptop | VGA")       side_by_side LVDS1 VGA1 ;;
  "VGA | Laptop")       side_by_side VGA1 LVDS1 ;;
  "Laptop | HDMI")      side_by_side LVDS1 HDMI1 ;;
  "HDMI | Laptop")      side_by_side HDMI1 LVDS1 ;;
  "Laptop | Dock HDMI") side_by_side LVDS1 HDMI2 ;;
  "Dock HDMI | Laptop") side_by_side HDMI2 LVDS1 ;;
  "Mirrored VGA")       mirror LVDS1 VGA1 ;;
  "Mirrored HDMI")      mirror LVDS1 HDMI1 ;;
  "Mirrored Dock HDMI") mirror LVDS1 HDMI2 ;;
  *)                    exit 0 ;;
esac

setxkbmap -option -option caps:swapescape
set-wallpaper
sleep 2 && killall -9 conky; conky --config $HOME/.conky/conkyrc
