#!/bin/sh

# Forked from
# The famous "get a menu of emojis to copy" script.
# https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/dmenuunicode
# GPLv3 - Luke Smith <luke@lukesmith.xyz>

# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/.local/share/fonts/emoji | dmenu -i -p emoji -l 20 | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
  xdotool key Shift+Insert
else
  echo "$chosen" | tr -d '\n' | xclip -selection clipboard
  notify-send "'$chosen' copied to clipboard." &
fi
