#!/bin/bash

# Invert an entire window class' colors via Compton
# GPLv3 - Grim Kriegor <grimkriegor@krutt.org>
# 2019

PID_FILE="/tmp/compton-inverted.pid"

if [[ -f $PID_FILE ]]; then
  pkill compton
  rm "$PID_FILE"
  compton &
else
  pkill compton
  ID=$(xdotool getactivewindow)
  CLASS=$(xprop -id "$ID"  | grep "WM_CLASS" | awk '{print $4}')
  COND="class_g=${CLASS}"
  compton --write-pid-path "$PID_FILE" --invert-color-include "$COND" &
fi
