#!/bin/sh

lock() {

    revert() {
        xset dpms 0 0 0
    }
    trap revert HUP INT TERM

    xset +dpms dpms 10 10 10
    sleep 1 && blackout

    (i3lock -n -c 000000 -e -f; revert) &
}

blackout() {
    xset dpms force off
}

case "$1" in
    lock)
        lock
        ;;
    blackout)
        blackout
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
        ;;
esac

exit 0
