#!/bin/bash

#################################################
# Quick file share                              #
# by Grim Kriegor (grimkriegor@krutt.org)       #
#################################################
# Last Revision: Aug 2017
#################################################

set -e

#Config
CONFIG_FILE="$HOME/.config/quick-file-share.conf"

if [ -f "$CONFIG_FILE" ]; then
  source "$CONFIG_FILE"
else
  echo -e "No config found. Generating new one.\nEdit \"$CONFIG_FILE\" to add your credentials."
  CONFIG_FILE_SKEL="USER=\"$(whoami)\"\nMACHINE=\"changeme\"\nPORT=\"22\"\nPREFIX=\"https://change.me/path/\"\nREMOTEPUBLIC=\"/var/www/$USER/path\""
  echo -e "$CONFIG_FILE_SKEL" > "$CONFIG_FILE"
  chmod 640 "$CONFIG_FILE"
  exit 0
fi

#Check filename
if [ "$1" != "" ]; then
  FILE="$1"
else
  exit 0
fi

#Encode URL
FILENAME=$(basename "$FILE")
FILENAMEENC=$(echo $FILENAME | sed -e 's/%/%25/g' -e 's/ /%20/g' -e 's/ /%09/g' -e 's/!/%21/g' -e 's/"/%22/g' -e 's/#/%23/g' -e 's/\$/%24/g' -e 's/\&/%26/g' -e 's/'\''/%27/g' -e 's/(/%28/g' -e 's/)/%29/g' -e 's/\*/%2a/g' -e 's/+/%2b/g' -e 's/,/%2c/g' -e 's/-/%2d/g' -e '#s/\./%2e/g' -e 's/\//%2f/g' -e 's/:/%3a/g' -e 's/;/%3b/g' -e 's//%3e/g' -e 's/?/%3f/g' -e 's/@/%40/g' -e 's/\[/%5b/g' -e 's/\\/%5c/g' -e 's/\]/%5d/g' -e 's/\^/%5e/g' -e 's/_/%5f/g' -e 's/`/%60/g' -e 's/{/%7b/g' -e 's/|/%7c/g' -e 's/}/%7d/g' -e 's/~/%7e/g' -e 's/      /%09/g')

#Upload
echo "Uploading $FILE"
scp -q -P$PORT "$FILE" $USER@$MACHINE:$REMOTEPUBLIC
ssh -q -p$PORT $USER@$MACHINE chmod 755 \"$REMOTEPUBLIC/${FILENAME}\"

#Send notifications and copy paste url
echo "$PREFIX/$FILENAMEENC"
notify-send "File avaliable at" "$PREFIX/$FILENAMEENC"
echo -n "$PREFIX/$FILENAMEENC" | xclip -selection clipboard
