#!/bin/bash
# Toggle touchpad. Requires xorg-xinput.

set -e

touchpad="SynPS/2 Synaptics TouchPad"
enabled="Device Enabled"

if (($(xinput list-props "$touchpad" | grep "$enabled" | cut -f3))); then
  xinput set-prop "$touchpad" "$enabled" 0
  echo "TouchPad deactivated."
else
  xinput set-prop "$touchpad" "$enabled" 1
  echo "TouchPad activated."
fi

