#!/bin/bash
# Toggle touchpad. Requires xf86-input-synaptics.

set -e

if [[ $(synclient | grep TouchpadOff.*1) ]]; then
  synclient TouchpadOff=0
  echo "TouchPad reactivated."
else
  synclient TouchpadOff=1
  echo "TouchPad deactivated."
fi

