#!/bin/bash

function getVideoTitle() {
  title=$(youtube-dl --get-title "$1")
  echo "$title"
}

args="$@"
clipboard_contents="$(xclip -selection c -o)"
type=""

path="$args"
if [[ $args == "" ]]; then
  path="$clipboard_contents"
fi

echo "$path" | grep -i 'youtube.com\|vimeo.com' \
  && type=webvideo
echo "$path" | grep -i 'twitch.tv' \
  && type=livestream
echo "$path" | grep -i '^magnet' \
  && type=magnet

case "$type" in

  webvideo )
    title="Web video"
    message="$(getVideoTitle $path)"
    mpv "$path" &
  ;;

  livestream )
    title="Livestream"
    message="$(getVideoTitle $path)"
    mpv "$path" &
  ;;

  magnet )
    title="Magnet link"
    message="Now streaming..."
    peerflix --mpv $path &
  ;;

esac

notify-send "${title:-Video Handler}" "${message:-Nothing to play}"
