#!/bin/bash

# Watch out for docking events
# and run dock-handler accordingly
# GPLv3 - Grim Kriegor <grimkriegor@krutt.org>
# 2019
#
# Usage:
# $ watchdock [interval] [dock display]

check_interval="${1:-5}"
dock_display="${2:-HDMI2}"
dock_test_script="$HOME/.config/dock-handler/check"

function isDocked() {
  if [[ -f $dock_test_script ]]; then
    test $(bash dock_test_script) && \
      return 0
    return 1
  else
    test $(xrandr | grep -w "connected" | awk -F'[ + ]' '{print $1}' | grep "$dock_display") && \
      return 0
    return 1
  fi
}

function checkState() {
  if isDocked; then
    echo "desktop"
  else
    echo "laptop"
  fi
}

function switchMode() {
  mode="$1"
  echo "Switching to mode: $mode"
  notify-send "watchdock" "Switching to mode: $mode"
  dock-handler "$mode" 2>&1 >/dev/null
}

current_state="$(checkState)"
previous_state="$current_state"
dock-handler "$current_state" 2>&1 >/dev/null
echo "Initializing in mode: $current_state"
notify-send "watchdock" "Initializing in mode: $current_state"

while true; do
  current_state="$(checkState)"
  [[ "$current_state" != "$previous_state" ]] && \
    switchMode "$current_state"
  previous_state="$current_state"
  sleep $check_interval
done

