#!/bin/bash


case "$1" in

  "360" )
    FORMAT="18"
  ;;

  "480" )
    FORMAT="135"
  ;;

  "720" )
    FORMAT="22"
  ;;

  "1080" )
    FORMAT="137"
  ;;

esac


VIDEO="$2"


eval mpv --ytdl-format="$FORMAT" "$VIDEO"
